// Pulls upstream-owned runtime inputs into the studio at dev/build time, so they
// track pascalorg/editor on every sync without being copied into git:
//   - apps/editor/public  -> studio/public   (item models, HDRIs, icons, audio)
//   - studio/static       -> studio/public   (our overrides, copied last)
//   - apps/editor/app/globals.css theme tokens -> app/upstream-theme.css
//   - styles/elevation.css                     -> app/upstream-elevation.css
// Turbopack's root is dt/, so nothing outside it can be imported directly.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const studioDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = path.resolve(studioDir, '../..')
const upstreamApp = path.join(repoRoot, 'apps/editor')
const publicDir = path.join(studioDir, 'public')
const staticDir = path.join(studioDir, 'static')

rmSync(publicDir, { recursive: true, force: true })
mkdirSync(publicDir, { recursive: true })
cpSync(path.join(upstreamApp, 'public'), publicDir, { recursive: true })
if (existsSync(staticDir)) cpSync(staticDir, publicDir, { recursive: true })

// Tailwind entry points and @source globs are relative to apps/editor, so they are
// dropped here and re-declared in app/globals.css against our own install root.
const theme = readFileSync(path.join(upstreamApp, 'app/globals.css'), 'utf8')
  .split('\n')
  .filter((line) => !/^@(import|source)\s/.test(line))
  .join('\n')
writeFileSync(
  path.join(studioDir, 'app/upstream-theme.css'),
  `/* Generated by scripts/sync-public.mjs from apps/editor/app/globals.css. Do not edit. */\n${theme}`,
)

cpSync(
  path.join(repoRoot, 'styles/elevation.css'),
  path.join(studioDir, 'app/upstream-elevation.css'),
)

console.log('[dt] synced upstream public assets and theme')
